version: '3'

services:
  api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    environment:
      - PORT=${PORT}
      - PUBLIC_PATH=${PUBLIC_PATH}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - ${PORT}:${PORT}
    restart: always
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432